### PR TITLE
Use sane Dockerfile

### PR DESCRIPTION
**Pull request by nemchik**
and support installing apk versions

Depends on https://github.com/linuxserver/docker-jenkins-builder/pull/95

### CODE REVIEW

**Comment by aptalca** [comment]
version mismatch between baseimage and package repo, 3.12 vs 3.13

**Comment by nemchik** [comment]
> version mismatch between baseimage and package repo, 3.12 vs 3.13

Fix pushed. Good catch.

**Comment by aptalca** [comment]
Jenkinsfile is injecting an md5sum instead of package version as a build arg

**Comment by nemchik** [comment]
> Jenkinsfile is injecting an md5sum instead of package version as a build arg

After https://github.com/linuxserver/docker-jenkins-builder/pull/95 it won't

**Review by aptalca — APPROVED** [review]

**Pull request merged**
